"""
house scenario for following_sim. Auto-generated by deploy_5_scenarios.py.
"""
from pathlib import Path

from launch import LaunchDescription
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.substitutions import FindPackageShare



def generate_launch_description():
    rviz_arg = DeclareLaunchArgument('rviz', default_value='false')
    gui_arg = DeclareLaunchArgument('gui', default_value='true')


    bringup = PathJoinSubstitution([
        FindPackageShare('following_sim'), 'launch', 'bringup.launch.py',
    ])

    return LaunchDescription([
        rviz_arg, gui_arg,
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(bringup),
            launch_arguments={
                'scenario': 'house',
                'robot_x': '-7.00',
                'robot_y': '0.00',
                'robot_yaw': '0.0000',
                'rviz': LaunchConfiguration('rviz'),
                'gui': LaunchConfiguration('gui'),
                'run_name': 'house',
                'worldgen_delay': '4.0',  
                'gazebo_delay': '8.0',  
                'spawn_delay': '20.0',  
                'bridge_delay': '22.0',  
                'perception_delay': '24.0',  
            }.items(),
        ),
    ])
