"""
small_house scenario for following_sim. Auto-generated by deploy_5_scenarios.py.
"""
from pathlib import Path

from launch import LaunchDescription
from launch.substitutions import EnvironmentVariable, LaunchConfiguration, PathJoinSubstitution
from launch.actions import (
    DeclareLaunchArgument, IncludeLaunchDescription, SetEnvironmentVariable,
)
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch_ros.substitutions import FindPackageShare


# Source checkout providing models referenced by `<uri>model://aws_robomaker_*</uri>`
_EXTRA_MODELS_DIR = Path("/home/glt/proj/human-following/ros2_following/aws-robomaker-small-house-world/models")


def generate_launch_description():
    rviz_arg = DeclareLaunchArgument('rviz', default_value='false')
    gui_arg = DeclareLaunchArgument('gui', default_value='true')


    set_extra_models = SetEnvironmentVariable(
        name='GAZEBO_MODEL_PATH',
        value=[str(_EXTRA_MODELS_DIR), ':',
               EnvironmentVariable('GAZEBO_MODEL_PATH', default_value='')],
    )

    bringup = PathJoinSubstitution([
        FindPackageShare('following_sim'), 'launch', 'bringup.launch.py',
    ])

    return LaunchDescription([
        rviz_arg, gui_arg,
        set_extra_models,
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(bringup),
            launch_arguments={
                'scenario': 'small_house',
                'robot_x': '-7.00',
                'robot_y': '0.00',
                'robot_yaw': '0.0000',
                'rviz': LaunchConfiguration('rviz'),
                'gui': LaunchConfiguration('gui'),
                'run_name': 'small_house',
                'worldgen_delay': '5.0',  
                'gazebo_delay': '10.0',  
                'spawn_delay': '28.0',  
                'bridge_delay': '30.0',  
                'perception_delay': '32.0',  
            }.items(),
        ),
    ])
